apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend_deployment.yaml
- backend_deployment.yaml
- logger_deployment.yaml
- demo_postgres_deployment.yaml
- logs_postgres_deployment.yaml
- init-testdata.yaml