apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-app
  template:
    metadata:
      labels:
        app: llm-app
    spec:
      containers:
      - name: llm-app
        image: 'quay.io/coen_de_vries/hcs-stage/llm-app:v2'
        ports:
        - containerPort: 8080

---

# Create a Service object for the frontend Deployment
apiVersion: v1
kind: Service
metadata:
  name: llm-app
spec:
  selector:
    app: llm-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

# Create a route for the frontend Service
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llm-app
spec:
  to:
    kind: Service
    name: llm-app
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect