apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: pgvector-pvc
          persistentVolumeClaim:
            claimName: pgvector-pvc
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: postgresql
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_DATABASE
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pgvector-pvc
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          image: 'quay.io/rh-aiservices-bu/postgresql-15-pgvector-c9s:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

---

kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: coen-de-vries-dev
type: Opaque
stringData:
  POSTGRESQL_USER: HCSuser
  POSTGRESQL_PASSWORD: HCSpassword
  POSTGRESQL_DATABASE: HCSinsurance

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3

---

apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
spec:
  template:
    spec:
      containers:
      - name: psql
        image: 'quay.io/rh-aiservices-bu/postgresql-15-pgvector-c9s:latest'
        command: ["/bin/sh","-c"]
        args: ["
          PGPASSWORD=HCSpassword psql -h postgresql -U postgres -f /scripts/activate-extension.sql; 
          PGPASSWORD=HCSpassword psql -h postgresql -d HCSinsurance -U HCSuser -f /scripts/HCSinsurance.sql; 
          PGPASSWORD=HCSpassword psql -h postgresql -d HCSinsurance -U HCSuser -f /scripts/logs.sql;
        "]
        volumeMounts:
        - name: sql-scripts
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: sql-scripts
        configMap:
          name: init-scripts

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
data:
  activate-extension.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;

    CREATE DATABASE logs WITH OWNER HCSuser;
  HCSinsurance.sql: |
    
  logs.sql : |
    CREATE DATABASE logs;