"""empty message

Revision ID: a0285e69206b
Revises: 5bedc4fe9414
Create Date: 2024-12-02 09:20:24.101787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0285e69206b'
down_revision = '5bedc4fe9414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('retrieved_documents', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    op.create_table('frontend_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    op.create_table('llm_with_rag_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('with_rag_answer', sa.String(length=255), nullable=False),
    sa.Column('with_rag_duration', sa.Time(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    op.create_table('llm_without_rag_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('without_rag_answer', sa.String(length=255), nullable=False),
    sa.Column('without_rag_duration', sa.Time(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_without_rag_logs')
    op.drop_table('llm_with_rag_logs')
    op.drop_table('frontend_logs')
    op.drop_table('backend_logs')
    # ### end Alembic commands ###
