# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt first for efficient caching
COPY requirements.txt .

# Install the required Python packages
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Switch to user 1001480000
USER 1001480000

# Copy the application code into the container
COPY . .

# Set the command to run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]