apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-etcd
  template:
    metadata:
      labels:
        app: milvus-etcd
    spec:
      containers:
      - name: milvus-etcd
        image: quay.io/coreos/etcd:v3.5.5
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_SNAPSHOT_COUNT
          value: "50000"
        command: ["etcd"]
        args: ["-advertise-client-urls=http://127.0.0.1:2379", "-listen-client-urls", "http://0.0.0.0:2379", "--data-dir", "/etcd"]
        volumeMounts:
        - mountPath: /etcd
          name: etcd-storage
        livenessProbe:
          exec:
            command: ["etcdctl", "endpoint", "health"]
          initialDelaySeconds: 30
          timeoutSeconds: 20
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: etcd-storage
        persistentVolumeClaim:
          claimName: etcd-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: milvus-etcd
