kind: Pod
apiVersion: v1
metadata:
  generateName: milvus-etcd-68695bb8fb-
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.116.18/23"],"mac_address":"0a:58:0a:80:74:12","gateway_ips":["10.128.116.1"],"routes":[{"dest":"10.128.0.0/16","nextHop":"10.128.116.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.116.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.116.1"}],"ip_address":"10.128.116.18/23","gateway_ip":"10.128.116.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.116.18"
          ],
          "mac": "0a:58:0a:80:74:12",
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container milvus-etcd; cpu, memory limit for container milvus-etcd'
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '2525427179'
  name: milvus-etcd-68695bb8fb-wqhfz
  uid: 9b5a511e-9018-4d42-80ab-b5b3ef623bd7
  creationTimestamp: '2024-10-04T06:01:10Z'
  managedFields:
    - manager: ip-10-0-196-170
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.ovn.org/pod-networks': {}
      subresource: status
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"04539034-de4b-44ac-83fa-f664a7753fcf"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"milvus-etcd"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/etcd"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:args': {}
              'f:command': {}
              'f:livenessProbe':
                .: {}
                'f:exec':
                  .: {}
                  'f:command': {}
                'f:failureThreshold': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:env':
                .: {}
                'k:{"name":"ETCD_AUTO_COMPACTION_MODE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ETCD_AUTO_COMPACTION_RETENTION"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ETCD_QUOTA_BACKEND_BYTES"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ETCD_SNAPSHOT_COUNT"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"etcd-storage"}':
              .: {}
              'f:name': {}
              'f:persistentVolumeClaim':
                .: {}
                'f:claimName': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"PodReadyToStartContainers"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:hostIPs': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.128.116.18"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
    - manager: multus-daemon
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
  namespace: coen-de-vries-dev
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: milvus-etcd-68695bb8fb
      uid: 04539034-de4b-44ac-83fa-f664a7753fcf
      controller: true
      blockOwnerDeletion: true
  labels:
    app: milvus-etcd
    pod-template-hash: 68695bb8fb
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-cxxht
  priority: -3
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-196-170.ec2.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c114,c14'
    fsGroup: 1012910000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: milvus-etcd
      command:
        - etcd
      livenessProbe:
        exec:
          command:
            - etcdctl
            - endpoint
            - health
        initialDelaySeconds: 30
        timeoutSeconds: 20
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: revision
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: '1000'
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: '4294967296'
        - name: ETCD_SNAPSHOT_COUNT
          value: '50000'
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1012910000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: etcd-storage
          mountPath: /etcd
        - name: kube-api-access-zttsh
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'quay.io/coreos/etcd:v3.5.5'
      args:
        - '-advertise-client-urls=http://127.0.0.1:2379'
        - '-listen-client-urls'
        - 'http://0.0.0.0:2379'
        - '--data-dir'
        - /etcd
  serviceAccount: default
  volumes:
    - name: etcd-storage
      persistentVolumeClaim:
        claimName: etcd-pvc
    - name: kube-api-access-zttsh
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: sandbox-users-pods
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: milvus-etcd
      state:
        running:
          startedAt: '2024-10-04T06:01:19Z'
      imageID: 'default-route-openshift-image-registry.apps.sandbox-m4.g2pi.p1.openshiftapps.com/coen-de-vries-dev/etcd@sha256:89b6debd43502d1088f3e02f39442fd3e951aa52bee846ed601cf4477114b89e'
      image: 'quay.io/coreos/etcd:v3.5.5'
      lastState: {}
      containerID: 'cri-o://b5919b6225cd10c66e9dda1820055e5fa714eb5fb7b2b18a7f4b93ed5bbbf0c1'
  qosClass: Burstable
  hostIPs:
    - ip: 10.0.196.170
  podIPs:
    - ip: 10.128.116.18
  podIP: 10.128.116.18
  hostIP: 10.0.196.170
  startTime: '2024-10-04T06:01:10Z'
  conditions:
    - type: PodReadyToStartContainers
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:19Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:10Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:19Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:19Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:10Z'
  phase: Running