apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-standalone
  template:
    metadata:
      labels:
        app: milvus-standalone
    spec:
      containers:
      - name: milvus-standalone
        image: milvusdb/milvus:v2.4.11
        command: ["milvus", "run", "standalone"]
        env:
        - name: ETCD_ENDPOINTS
          value: "milvus-etcd:2379"
        - name: MINIO_ADDRESS
          value: "milvus-minio:9000"
        volumeMounts:
        - mountPath: /var/lib/milvus
          name: milvus-storage
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 90
          timeoutSeconds: 20
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: milvus-storage
        persistentVolumeClaim:
          claimName: milvus-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
spec:
  ports:
  - port: 19530
    targetPort: 19530
    name: milvus-port
  - port: 9091
    targetPort: 9091
    name: milvus-health
  selector:
    app: milvus-standalone