apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-minio
  template:
    metadata:
      labels:
        app: milvus-minio
    spec:
      containers:
      - name: milvus-minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        command: ["minio", "server", "/minio_data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
          name: minio-port
        - containerPort: 9001
          name: minio-console
        volumeMounts:
        - mountPath: /minio_data
          name: minio-storage
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 20
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: minio-port
  - port: 9001
    targetPort: 9001
    name: minio-console
  selector:
    app: milvus-minio
