kind: Pod
apiVersion: v1
metadata:
  generateName: milvus-minio-66795b79bb-
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.116.19/23"],"mac_address":"0a:58:0a:80:74:13","gateway_ips":["10.128.116.1"],"routes":[{"dest":"10.128.0.0/16","nextHop":"10.128.116.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.116.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.116.1"}],"ip_address":"10.128.116.19/23","gateway_ip":"10.128.116.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.116.19"
          ],
          "mac": "0a:58:0a:80:74:13",
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container milvus-minio; cpu, memory limit for container milvus-minio'
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '2525427270'
  name: milvus-minio-66795b79bb-hqkfr
  uid: 715404d9-ce8c-49c3-bb50-4ed7ebc17e9c
  creationTimestamp: '2024-10-04T06:01:13Z'
  managedFields:
    - manager: ip-10-0-196-170
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.ovn.org/pod-networks': {}
      subresource: status
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"d0e29a64-ee1b-408d-b8dc-762727ec63eb"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"milvus-minio"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/minio_data"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:livenessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:env':
                .: {}
                'k:{"name":"MINIO_ACCESS_KEY"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"MINIO_SECRET_KEY"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":9000,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
                'k:{"containerPort":9001,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"minio-storage"}':
              .: {}
              'f:name': {}
              'f:persistentVolumeClaim':
                .: {}
                'f:claimName': {}
    - manager: multus-daemon
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2024-10-04T06:01:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"PodReadyToStartContainers"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:hostIPs': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.128.116.19"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: coen-de-vries-dev
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: milvus-minio-66795b79bb
      uid: d0e29a64-ee1b-408d-b8dc-762727ec63eb
      controller: true
      blockOwnerDeletion: true
  labels:
    app: milvus-minio
    pod-template-hash: 66795b79bb
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-cxxht
  priority: -3
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-196-170.ec2.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c114,c14'
    fsGroup: 1012910000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: milvus-minio
      command:
        - minio
        - server
        - /minio_data
        - '--console-address'
        - ':9001'
      livenessProbe:
        httpGet:
          path: /minio/health/live
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 20
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1012910000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - name: minio-port
          containerPort: 9000
          protocol: TCP
        - name: minio-console
          containerPort: 9001
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: minio-storage
          mountPath: /minio_data
        - name: kube-api-access-g2n57
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'minio/minio:RELEASE.2023-03-20T20-16-18Z'
  serviceAccount: default
  volumes:
    - name: minio-storage
      persistentVolumeClaim:
        claimName: minio-pvc
    - name: kube-api-access-g2n57
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: sandbox-users-pods
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: milvus-minio
      state:
        running:
          startedAt: '2024-10-04T06:01:19Z'
      imageID: 'default-route-openshift-image-registry.apps.sandbox-m4.g2pi.p1.openshiftapps.com/coen-de-vries-dev/minio@sha256:6150a378e4636a713209465c57045cacac0ee0ecb0b72f5d23da4314145aa0d4'
      image: 'docker.io/minio/minio:RELEASE.2023-03-20T20-16-18Z'
      lastState: {}
      containerID: 'cri-o://b16c6a0d0baf2556eee190fab467a0eb5aaed616d1549f019624439263a8f349'
  qosClass: Burstable
  hostIPs:
    - ip: 10.0.196.170
  podIPs:
    - ip: 10.128.116.19
  podIP: 10.128.116.19
  hostIP: 10.0.196.170
  startTime: '2024-10-04T06:01:13Z'
  conditions:
    - type: PodReadyToStartContainers
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:20Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:13Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:20Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:20Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-10-04T06:01:13Z'
  phase: Running