# Use the provided PostgreSQL image with pgvector
FROM quay.io/rh-aiservices-bu/postgresql-15-pgvector-c9s:latest

#Mount sql scripts to the container
COPY sql-scripts/HCSinsurance.sql /docker-entrypoint-initdb.d/
COPY sql-scripts/logs.sql /docker-entrypoint-initdb.d/