apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
        - name: pgvector
          image: pgvector/pgvector:pg17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESQL_DATABASE
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgvector-storage
      volumes:
        - name: pgvector-storage
          persistentVolumeClaim:
            claimName: pgvector-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: pgvector
spec:
  selector:
    app: pgvector # Matches the pod labels in the Deployment
  ports:
    - protocol: TCP
      port: 5432 # Port exposed by the service
      targetPort: 5432 # Container port
  type: ClusterIP # Internal access only; change to LoadBalancer or NodePort for external access