"""No capital letters v2

Revision ID: 44255fe6f458
Revises: ca5132056a13
Create Date: 2024-10-23 15:23:37.864419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44255fe6f458'
down_revision = 'ca5132056a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licenseplate', sa.String(length=8), nullable=False))
        batch_op.drop_column('licensePlate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licensePlate', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.drop_column('licenseplate')

    # ### end Alembic commands ###
