"""Updated models

Revision ID: 83bcc15c7ade
Revises: 6d5123f1ce2b
Create Date: 2024-10-23 11:05:34.218148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bcc15c7ade'
down_revision = '6d5123f1ce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurancePolicy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'insurance_policy', ['insurancePolicy_id'], ['id'])

    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('insurancePolicy_id')

    # ### end Alembic commands ###
