"""added summary

Revision ID: c9ec6fe79cf0
Revises: 44255fe6f458
Create Date: 2024-10-24 10:45:07.969491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ec6fe79cf0'
down_revision = '44255fe6f458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
