"""No capital letters

Revision ID: ca5132056a13
Revises: 83bcc15c7ade
Create Date: 2024-10-23 13:16:01.013077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5132056a13'
down_revision = '83bcc15c7ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurancepolicy_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('car_insurancePolicy_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'insurance_policy', ['insurancepolicy_id'], ['id'])
        batch_op.drop_column('insurancePolicy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurancePolicy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('car_insurancePolicy_id_fkey', 'insurance_policy', ['insurancePolicy_id'], ['id'])
        batch_op.drop_column('insurancepolicy_id')

    # ### end Alembic commands ###
